### ISSUE TITLE
Linting should only be done for Python

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#61]
It is a lot of unnecessary work in r to handle whitespace. Since R doesn't use whitespace in syntax it doesn't matter much, but we could direct the linting tests to the python folder. But now it is just a hassle to get failing test because of this so I disable that test in Travis file.

**Comment by eerolinna** [comment]
I can later give reasons why we really want to remove the trailing whitespace, but for now I'll just say this. The removal of trailing whitespace is not related to python in any way. Python doesn't care about trailing whitespace.

It should not be a lot of work to do this in R. In RStudio enable the settings **Strip trailing horizontal whitespace when saving** and **Ensure that source files end with a new line** and you should not have to worry about anymore. See https://support.rstudio.com/hc/en-us/articles/200549016-Customizing-RStudio?mobile_site=true for more

Can you try doing this and seeing if you still end up with trailing whitespace in the commits?

**Comment by MansMeg** [comment]
I can see if this works yes. If it is just to run the code in the PR it is reasonable.

**Comment by eerolinna** [comment]
Okey, so I guess how you currently feel is this (feel free to correct)

- You agree that having no trailing whitespace is better than having it
- But it is extra hassle and the value gained is less than the hassle of it

The way we can change the equation is by decreasing the hassle or increasing the perceived value. I will outline some ways here. However note that I'm **not** advocating for keeping these checks at all costs. I just want us to have a shared understanding so we can make an informed decision. If we agree that it's better to disable these checks for the R files then I will prepare a PR that does so.

## The hassle
I agree that if you only fix these problems when the CI has failed it is indeed too big of an hassle. However if you configure RStudio to remove the problems automatically when you save a file (see my post above) I don't see any hassle at all.

## The benefits

### Cleaner git diffs

Imagine if this diff contained also real changes: https://github.com/MansMeg/posteriordb/pull/62/commits/f8998a52fa1131d912e1317d9bcebff023126aa3 It will be more difficult to spot them from the noise of whitespace changes

### Less hassle when making commits
This is a real-life situation from a previous company. We had a large file of webpage view definitions (several thousands of lines, there were also other files this long) that had a lot of unnecessary trailing whitespace. I had configured my editor to remove trailing whitespace. I added one function to the file and this resulted in a massive commit because of the removed whitespace. I didn't want to a diff like that so I had to go out of my way to add only my actual changes (so essentially carefully only stage the parts I actually had modified and then discard the whitespace changes). I had to do this every time I edited this large file.

Looking back, perhaps the right thing to do would have been to create a massive commit that removed all trailing whitespace and perhaps after that add a CI test that would enforce no extra trailing whitespace. However that massive commit would have destroyed `git blame` and also some of the devs had not configured their editor to strip the extra whitespace so either the problem would slowly have crept in again or I would have had to spend extra time convincing them to change their editor configuration. Another reason I didn't go with the massive commit was just inertia: there was no culture of "leaving the campground better than you found it" and no one had done big changes like this before.

In our case we are in a good situation right now: almost all files are in good condition and we have the cabability to enforce that they stay this way (if we choose to do it). When we review PRs of potential contributors we won't need to spend time asking them to change marginal details with the formatting when CI can alert the contributors to make these changes before asking for a review.

We also won't need to worry about accidently leaving some additional whitespace behind ourselves (lets say we are temporarily working on another computer and use an unfamiliar editor) because CI will catch it. However if we disable the checks there's a good chance that we will over time end up in a situation where the files might have a lot of extra whitespace. Then the contributors and us will either have to spend unnecessary effort to keep clean diffs or make commits that contain a lot of noise and destroy the ability to use `git blame` to easily find when a change to some line was made.

The only price we really have to pay is the one-time effort of changing the settings of our editor to do these changes automatically on save.

I would appreciate it if you can try changing the settings of RStudio so that we can both keep the R files clean and do it without hassle. However if you want me to disable these checks for the R files I will do so.

**Comment by eerolinna** [comment]
> I can see if this works yes. If it is just to run the code in the PR it is reasonable.

Yes if CI complains about the linting/general checks you can always just run the code in the PR to autofix the errors.

**Comment by MansMeg** [comment]
Ok. This is a hassle in my workflow to do pre-commits so that is not worth removing whitespace for. I have changed my R-Studio settings so that will be fixed now. Lets see if it is still a hassle. If so we should disable the CI tests. You are of course welcome to do cleaning of the whole repo if you like.

**Comment by eerolinna** [comment]
> Ok. This is a hassle in my workflow to do pre-commits so that is not worth removing whitespace for.

I'm not fully sure what you mean here? Do you mean it's an hassle to run the fixer script every time before you commit? Or do you mean the slight delay caused by pre-commit checks?

**Comment by MansMeg** [comment]
Yes. I use git through rstudio so running it before everytime is too much hassle.

**Comment by eerolinna** [comment]
Ah, the pre-commit checks don't require you to use git from the command line. RStudio git should work just fine.

To clarify once you have installed the pre-commit checks (by running `pre-commit install`) the checks will be run when you commit using RStudio, there is no need to either run them manually or to use command line git.

For this particular case you probably won't need the pre-commit checks because the RStudio settings you enabled should take care of the issue. However if you install the checks you can be sure that your commits won't fail on the CI linting job. For example if you edit some of the python code it would be helpful to have the pre-commit checks installed because the checks autoformat python code, which RStudio won't do.

Essentially what I'm saying is that you probably won't need the pre-commit hooks now but using them doesn't require changing your workflow.

**Comment by MansMeg** [comment]
Alright. I got this to work now with pre-commit, indeed quite comfortable. So now Im all in. Now it also make sense to have that as a test.
